version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g jsdoc

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
