version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
    nodejs: "16"
  apt_packages:
    - jsdoc-toolkit

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
