# Release process with pre-built wheels:
#  - Prep:
#    - in pyproject.toml, adjust the list of Python versions in classifiers and
#      tool.cobuildwheel.build
#    - in tests.yml, adjust python-version list; run the tests.yml workflow
#  - Test: dispatch this workflow manually and inspect the results
#  - Publish: create a release in the GitHub GUI, which will trigger this workflow,
#    including Trusted Publishing to PyPI

name: Build

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  list_all_artifacts:
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - run: ls -lR dist

  upload_pypi:
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    # Comment this line for testing
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v8
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        # Uncomment these lines for testing
        # with:
        #   repository-url: https://test.pypi.org/legacy/
