name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          sudo apt-get install sox ninja-build
      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run tests
        run: |
          CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target check

  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip3 install .[dev]
      - run: python3 -m pytest

  nodetest:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        uses: mymindstorm/setup-emsdk@v14
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          emcmake cmake -S . -B jsbuild
          cmake --build jsbuild
      - name: Run tests
        run: |
          (cd jsbuild && npm install --also=dev)
          (cd jsbuild && npm test)
          (cd jsbuild && npm run tstest)
