name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          sudo apt-get install sox ninja-build
      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run tests
        run: |
          CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target check
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          pip install -r requirements.dev.txt
          pip install .
      - name: Run tests
        run: pytest
  wintest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          pip install -r requirements.dev.txt
          pip install .
      - name: Run tests
        run: pytest
  mactest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          pip install -r requirements.dev.txt
          pip install .
      - name: Run tests
        run: pytest
  nodetest:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        uses: mymindstorm/setup-emsdk@v11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          emcmake cmake -S . -B jsbuild
          cmake --build jsbuild
      - name: Run tests
        run: |
          (cd jsbuild && npm install --also=dev)
          (cd jsbuild && npm test)
          (cd jsbuild && npm run tstest)
